version: '3.8'

services:
  papercord:
    image: ghcr.io/${GITHUB_USERNAME}/papercord:latest
    container_name: papercord
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
      - PRICE_CACHE_EXPIRATION_SECONDS=60
    volumes:
      - ./data:/app/data
    # Healthcheck to ensure the bot is running properly
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(process.uptime() < 30 ? 1 : 0)"]
      interval: 60s
      timeout: 10s
      retries: 3